// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingManagement.CourseApi.Models;

#nullable disable

namespace TrainingManagement.CourseApi.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    partial class CourseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("TrainingManagement.CourseApi.Data.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseDescription = "Learn the basics of C#",
                            CourseName = "C# Basics",
                            Duration = 10
                        },
                        new
                        {
                            CourseId = 2,
                            CourseDescription = "Learn how to build web applications with ASP.NET Core",
                            CourseName = "ASP.NET Core",
                            Duration = 15
                        },
                        new
                        {
                            CourseId = 3,
                            CourseDescription = "Learn how to use Entity Framework Core for data access",
                            CourseName = "Entity Framework Core",
                            Duration = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
