@TrainingManagement.CourseApi_HostAddress = http://localhost:5282

GET {{TrainingManagement.CourseApi_HostAddress}}/weatherforecast/
Accept: application/json

# GET {{TrainingManagement.CourseApi_HostAddress}}/CourseApi/
# Accept: application/json 

###
